// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLdlzvIbNXz9ar0D3mBgDdcbq8AYkrBSI',
    appId: '1:443243557930:web:385a256b88928797217f53',
    messagingSenderId: '443243557930',
    projectId: 'fir-getset-b2693',
    authDomain: 'fir-getset-b2693.firebaseapp.com',
    storageBucket: 'fir-getset-b2693.appspot.com',
    measurementId: 'G-LW6FPDDKYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxkSjRaYKOAMqOvVcWj8mRfPyVypqxHBI',
    appId: '1:443243557930:android:65091dd56714f51d217f53',
    messagingSenderId: '443243557930',
    projectId: 'fir-getset-b2693',
    storageBucket: 'fir-getset-b2693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwYf9WvUIOSLCN0iLbQXbcN1W8EyyyYZM',
    appId: '1:443243557930:ios:47bd8a2bcefff329217f53',
    messagingSenderId: '443243557930',
    projectId: 'fir-getset-b2693',
    storageBucket: 'fir-getset-b2693.appspot.com',
    iosBundleId: 'com.micro.firebaseGetset',
  );
}
